server:
  servlet:
    context-path: /my-api
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
springdoc:
  pathsToMatch:
    /person/v1/**,
    /person/v2/**,
    /book/v1/**,
    /math/**,
    /auth/**
  swagger-ui:
    use-root-path: true
